apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: public.ecr.aws/n4f2g6n0/studentapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # Ensure this matches the port your Spring Boot app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080 # Ensure this matches the container port your app listens on
    protocol: TCP
  selector:
    app: springboot-app
